# Generated by Django 3.2.9 on 2021-11-15 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0006_plandiscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'ALL QUESTIONS'},
        ),
    ]
