# Generated by Django 3.2.9 on 2021-11-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0008_auto_20211114_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subplanfeature',
            options={'verbose_name': 'Detalhes do plano do site '},
        ),
    ]
