# Generated by Django 3.2.9 on 2021-11-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0009_alter_subplanfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subplanfeature',
            options={'verbose_name_plural': 'Detalhes do plano do site'},
        ),
    ]
