# Generated by Django 3.2.9 on 2021-11-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0010_alter_subplanfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners do site'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Perguntas frequentes'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Rodapé do site'},
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name_plural': 'Formulário'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': 'Galerias'},
        ),
        migrations.AlterModelOptions(
            name='galeriafotos',
            options={'verbose_name_plural': 'Galeria (Fotos)'},
        ),
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name_plural': 'Páginas editáveis'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name_plural': 'Serviços do site'},
        ),
        migrations.AlterModelOptions(
            name='subplan',
            options={'verbose_name_plural': 'Planos do site'},
        ),
    ]
