# Generated by Django 3.2.9 on 2021-11-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0011_auto_20211114_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandiscount',
            options={'verbose_name_plural': 'Descontos dos planos'},
        ),
    ]
