# Generated by Django 3.2.9 on 2021-11-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0012_alter_plandiscount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandiscount',
            options={'verbose_name_plural': 'Descontos (Planos)'},
        ),
        migrations.AlterModelOptions(
            name='subplanfeature',
            options={'verbose_name_plural': 'Detalhes (Planos)'},
        ),
    ]
