# Generated by Django 3.2.9 on 2021-11-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0013_auto_20211114_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandiscount',
            name='subplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academiafitApp.subplan', verbose_name='Plano'),
        ),
    ]
