# Generated by Django 3.2.9 on 2021-11-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0016_subplan_validity_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subplan',
            old_name='preco',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='subplan',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subplanfeature',
            old_name='titulo',
            new_name='title',
        ),
    ]
