# Generated by Django 3.2.9 on 2021-11-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0017_auto_20211115_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
