# Generated by Django 3.2.9 on 2021-11-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0020_rename_plano_subscription_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='preco',
            new_name='price',
        ),
    ]
