# Generated by Django 3.2.9 on 2021-11-16 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0027_notifuserstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academiafitApp.cliente')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academiafitApp.trainer')),
            ],
        ),
    ]
