# Generated by Django 3.2.9 on 2021-11-16 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0028_assigncliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigncliente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='assigncliente',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academiafitApp.cliente'),
        ),
    ]
