# Generated by Django 3.2.9 on 2021-11-16 04:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academiafitApp', '0029_auto_20211116_0143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignCliente',
            new_name='AssignSubscriber',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Subscriber',
        ),
    ]
