# Generated by Django 3.2.9 on 2021-11-22 17:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0039_appsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosPaginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academiafitApp.servicos')),
            ],
            options={
                'verbose_name_plural': 'Páginas do Serviço',
            },
        ),
    ]
