# Generated by Django 3.2.9 on 2021-11-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0040_servicospaginas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicospaginas',
            old_name='servico',
            new_name='servicopagina',
        ),
    ]
