# Generated by Django 3.2.9 on 2021-11-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0041_rename_servico_servicospaginas_servicopagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicospaginas',
            name='servicopagina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academiafitApp.servicos'),
        ),
    ]
