# Generated by Django 3.2.9 on 2021-12-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiafitApp', '0043_auto_20211205_2303'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicosPaginas',
        ),
    ]
